### PR TITLE
Added metadata option to the Event

### PR DESCRIPTION
**Pull request by cossou**
The construct function changed, so there will be a break in compatibility.

### CODE REVIEW

**Comment by rgazelot** [comment]
Hi thanks for you suggest.

I think that the event Metadata has a complete logic and can be externalized to a proper class and passed to the construct as you suggest.

I will open a new PR for add this Metadata class.

**Comment by cossou** [comment]
Thanks, Rémy!

**Comment by rgazelot** [comment]
What do you think about #6 ?

**Comment by rgazelot** [comment]
I close because the feature was merged in master in #6

**Pull request closed without merging**
